[package]
name = "daphnis"
version = "0.1.0"
authors = ["Michael Byrne <16238945+MichaelByrneAU@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = "0.21.0"
indicatif = "0.11.0"
rand = "0.6.5"